plugins {
    id 'java'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.63-stable'
    implementation 'fr.citedesiles:cdi2-core-plugin:1.0.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}