name: cdi2-land-plugin
version: 1.0.0
main: fr.citedesiles.landplugin.LandPlugin
api-version: '1.21'
author: Azrotho

commands:
  corruption:
    description: Gestion de la corruption
    usage: /corruption <start|stop|pause|speed|spawnwarden>